<?php

use Illuminate\Database\Seeder;

class DetailsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('details')->insert([
            [
                'products_id' => 1,
                'details_title' => 'Laravel参考書',
                'categories_id' => 6,
                'details_description' => 'めちゃくちゃ面白い本です。最初に買って読んだときはゲラゲラ笑っていました。',
                'details_price' => 1000,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 5,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 2,
                'details_title' => '応用情報でるとこ',
                'categories_id' => 6,
                'details_description' => 'めちゃくちゃ面白い本です。最初に買って読んだときはゲラゲラ笑っていました。',
                'details_price' => 2100,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 3,
                'details_title' => 'チョコレート',
                'categories_id' => 5,
                'details_description' => 'ハリーポッターに出てくるチョコレートです。ダンブルドアが出てくると良いですね。',
                'details_price' => 300,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 4,
                'details_title' => 'ベビーバウンサー NewYorkBaby',
                'categories_id' => 3,
                'details_description' => 'かわいいトイ付き＆おしゃれなデニム生地のバウンサー♪
                絶妙なカーブでゆらゆら揺れて赤ちゃんごきげん！
                遊び・お昼寝・お食事さまざまなシーンで活躍します。
                面倒な組み立ての必要もなく、トイバーとホロをセットすればすぐに使えます。
                出産祝いのプレゼントなどにもおすすめです。',
                'details_price' => 5000,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 3,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 5,
                'details_title' => 'TAOTRONICS Bluetooth イヤホン',
                'categories_id' => 6,
                'details_description' => 'TAOTRONICSのBluetoothイヤホンになります。中古品になります。クリーニングしたのち発送いたします。動作確認済みです。',
                'details_price' => 4000,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 4,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 6,
                'details_title' => 'CURBX　エイムリング　130',
                'categories_id' => 6,
                'details_description' => 'CURBXのエイムリングになります。硬さは130です。使っていないものを出品します。新品未使用です。',
                'details_price' => 1500,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 7,
                'details_title' => 'レディース　パンツ',
                'categories_id' => 1,
                'details_description' => 'レディースのパンツになります。買ったっきり一度も使用していないため、きれいなほうだと思います。',
                'details_price' => 2000,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 8,
                'details_title' => 'メンズ　ジャケット　革ジャン',
                'categories_id' => 2,
                'details_description' => 'メンズの革ジャンになります。息子が使用しているもので小さくなったため出品致します。サイズはSです。ところどころ傷があります。',
                'details_price' => 1000,
                'details_state' => 3,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 9,
                'details_title' => 'ポニョ　ぬいぐるみ',
                'categories_id' => 3,
                'details_description' => 'ポニョのぬいぐるみになります。頂きもので袋に入れたままだった為きれいだと思います。',
                'details_price' => 400,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 4,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 10,
                'details_title' => '小型加湿器',
                'categories_id' => 4,
                'details_description' => '小型の加湿器になります。デザインが気に入り購入したものの加湿器としては一度も使用していません。動作確認済みではありませんが、ご了承ください。充電式です。',
                'details_price' => 700,
                'details_state' => 1,
                'details_shipping_fee' => 0,
                'details_area' => 3,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 11,
                'details_title' => 'ドラゴンズ　応援バット',
                'categories_id' => 5,
                'details_description' => 'ドラゴンズの応援バットになります。ナゴヤドームで買って一度使用したのち自宅で保管していました。',
                'details_price' => 400,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 12,
                'details_title' => 'iphone6',
                'categories_id' => 7,
                'details_description' => 'iphone6になります。携帯の買い替えのため使わなくなったため出品致します。フィルムに傷はありますが画面には傷等はありません。本体横は点々と剥げている箇所があります。中古品ですのでご理解のある方のご購入お願い致します。',
                'details_price' => 3000,
                'details_state' => 4,
                'details_shipping_fee' => 1,
                'details_area' => 7,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 13,
                'details_title' => 'レディース　バッグ',
                'categories_id' => 1,
                'details_description' => 'RODEOCROWNSのバッグになります。一度使用し自宅で保管していました。',
                'details_price' => 1000,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 6,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 14,
                'details_title' => 'メンズ　ジャケット',
                'categories_id' => 2,
                'details_description' => 'メンズのジャケットになります。サイズはSです。',
                'details_price' => 5000,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 3,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 15,
                'details_title' => 'シューズ袋　IGNIO',
                'categories_id' => 5,
                'details_description' => 'IGNIOのシューズ袋になります。体育館シューズなどが入ります。',
                'details_price' => 400,
                'details_state' => 4,
                'details_shipping_fee' => 0,
                'details_area' => 5,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 16,
                'details_title' => 'スキー手袋',
                'categories_id' => 5,
                'details_description' => 'スキー手袋になります。防水厚手なので普段使いも可能です。3で程使用しています。選択したのち配送させていただきます。',
                'details_price' => 400,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 8,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 17,
                'details_title' => 'とんでもスキルで異世界放浪メシ 6巻',
                'categories_id' => 6,
                'details_description' => 'とんでもスキルで異世界放浪メシの6巻です。一度読みそのまま保管していました。日焼け等はありません',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 18,
                'details_title' => '関数電卓',
                'categories_id' => 7,
                'details_description' => '関数電卓　傷なし汚れあり　3年間使いました',
                'details_price' => 500,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 19,
                'details_title' => '電子辞書',
                'categories_id' => 7,
                'details_description' => '画面が汚れています。　返品は受け付けません。',
                'details_price' => 300,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 20,
                'details_title' => '折り畳み式タッチパッド付きキーボード',
                'categories_id' => 7,
                'details_description' => 'ほぼ新品です。　便利です。',
                'details_price' => 1000,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 21,
                'details_title' => 'ねんどろいど　まふまふ(引きこもりセット)',
                'categories_id' => 6,
                'details_description' => '未開封の新品です。',
                'details_price' => 1500,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 22,
                'details_title' => '一番くじ　すみっコぐらし　ぬいぐるみ',
                'categories_id' => 4,
                'details_description' => '未開封の新品です。　かわいいです。',
                'details_price' => 2000,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 23,
                'details_title' => '手回し発電搭載　多機能防災時計',
                'categories_id' => 7,
                'details_description' => '災害用の手回し充電の多機能防災時計です。　ライトも付いてます。',
                'details_price' => 1000,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 24,
                'details_title' => 'RAGE2',
                'categories_id' => 6,
                'details_description' => 'PS4のゲームソフトです。対象年齢18歳以上です。',
                'details_price' => 500,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 25,
                'details_title' => 'FARCRY3+4 ダブルパック',
                'categories_id' => 6,
                'details_description' => 'PS4のゲームソフトです。FARCRY3とFARCRY4のセットパックです。対象年齢18歳以上です。',
                'details_price' => 700,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 26,
                'details_title' => 'iPhone6s',
                'categories_id' => 7,
                'details_description' => '64GB、ゴールドです。イヤホンジャックのところに多少傷があります。動作問題なし。',
                'details_price' => 3000,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 27,
                'details_title' => 'ヒバニー　ぬいぐるみ',
                'categories_id' => 4,
                'details_description' => 'ポケットモンスター剣盾に登場するヒバニーのぬいぐるみです。',
                'details_price' => 2000,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 28,
                'details_title' => 'コンデンサマイク',
                'categories_id' => 7,
                'details_description' => '開封済みですが傷なし汚れなしのほぼ新品です。音質もいいです。',
                'details_price' => 3000,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 29,
                'details_title' => 'Nintendo64 時のオカリナ',
                'categories_id' => 6,
                'details_description' => 'Nintendo64のゲームソフト、時のオカリナです。謎解きが楽しいです。',
                'details_price' => 500,
                'details_state' => 3,
                'details_shipping_fee' => 1,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 30,
                'details_title' => '3DS',
                'categories_id' => 6,
                'details_description' => 'Nintendo3DS本体です。傷、汚れ多少あり。動作問題なし。',
                'details_price' => 500,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 31,
                'details_title' => 'Android AQUOS Xx-Y',
                'categories_id' => 7,
                'details_description' => 'AQUOS Xx-Yのスマートフォンです。フィルムに傷はありますが画面には傷はありません。動作も問題ないです。',
                'details_price' => 4000,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 1,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 32,
                'details_title' => 'ジーンズ',
                'categories_id' => 1,
                'details_description' => 'レディースのジーンズです。未使用品です。',
                'details_price' => 1000,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 3,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 33,
                'details_title' => '東京喰種 1巻',
                'categories_id' => 6,
                'details_description' => '東京喰種の1巻です。汚れ、傷はありません。',
                'details_price' => 300,
                'details_state' => 1,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 34,
                'details_title' => 'メンズ　ジャンパー',
                'categories_id' => 2,
                'details_description' => 'メンズのジャンパーです。サイズはMで未使用品です。',
                'details_price' => 1000,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 3,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 35,
                'details_title' => 'アディダス　バッグ',
                'categories_id' => 5,
                'details_description' => 'アディダスのバッグです。息子が使っていたものなので少し傷があります。',
                'details_price' => 500,
                'details_state' => 4,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 36,
                'details_title' => '目覚まし時計',
                'categories_id' => 4,
                'details_description' => '目覚まし時計です。特に問題なく動作します。',
                'details_price' => 500,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 1,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 37,
                'details_title' => 'PS4　コントローラー',
                'categories_id' => 6,
                'details_description' => 'PS4のコントローラーです。一度しか使用していないので動作不良はありません。',
                'details_price' => 3000,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 0,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 38,
                'details_title' => 'USBメモリ 16GB',
                'categories_id' => 7,
                'details_description' => '16GBのUSBメモリです。フォーマット済みです。',
                'details_price' => 1000,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 2,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 39,
                'details_title' => '手袋',
                'categories_id' => 2,
                'details_description' => 'メンズの手袋です。所々に傷があります。',
                'details_price' => 500,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 3,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 40,
                'details_title' => 'ペン立て',
                'categories_id' => 4,
                'details_description' => 'ペン立てです。目立つ変形、傷などは特に見当たりません。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 4,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 41,
                'details_title' => 'ストラップ',
                'categories_id' => 3,
                'details_description' => 'アイルーのストラップです。未開封品です。',
                'details_price' => 100,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 4,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 42,
                'details_title' => 'イヤホン　iPhone用',
                'categories_id' => 7,
                'details_description' => 'イヤホンです。iPhoneの付属品で、未使用品です。',
                'details_price' => 500,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],

















            [
                'products_id' => 43,
                'details_title' => 'Panasonic QE-QL202 モバイルバッテリー',
                'categories_id' => 7,
                'details_description' => 'Panasonic QE-QL202 モバイルバッテリーです。5年ほど前に購入しました。5800mAhあります。表面はかなり傷ついています',
                'details_price' => 500,
                'details_state' => 4,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 44,
                'details_title' => '目覚まし時計　置き型',
                'categories_id' => 4,
                'details_description' => '目覚まし時計になります。音、画面表示ともに問題なく使えます。',
                'details_price' => 300,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 45,
                'details_title' => 'エルモ　カチューシャ',
                'categories_id' => 1,
                'details_description' => 'エルモのカチューシャになります。USJに行った際に買いました。一度だけ使用し、自宅で保管していました。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 2,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 46,
                'details_title' => 'ぬいぐるみ　ハリネズミ',
                'categories_id' => 3,
                'details_description' => 'ハリネズミのぬいぐるみになります。頂いたものの袋から出さずに保管していました。きれいなほうだと思います。',
                'details_price' => 400,
                'details_state' => 1,
                'details_shipping_fee' => 0,
                'details_area' => 3,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 47,
                'details_title' => 'ぬいぐるみ　イーヨー',
                'categories_id' => 3,
                'details_description' => 'イーヨーのぬいぐるみになります。頂いたものの袋から出さずに保管していました。きれいなほうだと思います。',
                'details_price' => 500,
                'details_state' => 1,
                'details_shipping_fee' => 0,
                'details_area' => 4,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 48,
                'details_title' => '腕時計　JAXIS',
                'categories_id' => 5,
                'details_description' => '腕時計になります。ランニングの際に使用していました。腕にフィットしやすいため運動に向いていると思います。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 49,
                'details_title' => 'HTML CSS JavaScript ホームページ辞典',
                'categories_id' => 6,
                'details_description' => '買ったはいいものの一度も使わず保管していました。日焼け等はありません。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 6,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 50,
                'details_title' => 'ウェストポーチ　Active Wear',
                'categories_id' => 2,
                'details_description' => '小物が入るカバンです。長財布等は余裕で入ります。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 7,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 51,
                'details_title' => '余命10年　小坂流加',
                'categories_id' => 6,
                'details_description' => '一度だけ読み保管していました。日焼け等はありません。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 8,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 52,
                'details_title' => '船を編む　三浦しをん',
                'categories_id' => 6,
                'details_description' => '一度だけ読み保管していました。日焼け等はありません。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 53,
                'details_title' => '折り畳み傘',
                'categories_id' => 2,
                'details_description' => '折り畳み傘です。持ち手のところが破損しています。',
                'details_price' => 300,
                'details_state' => 4,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 54,
                'details_title' => 'ハンディーファン',
                'categories_id' => 7,
                'details_description' => '手持ちの扇風機です。充電型で充電も長持ちします。',
                'details_price' => 400,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 2,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 55,
                'details_title' => '電子辞書　CASIO',
                'categories_id' => 7,
                'details_description' => 'CASIOの電子辞書になります。高校で使う辞書はだいたい入っています。高校時代に使用していました。',
                'details_price' => 700,
                'details_state' => 3,
                'details_shipping_fee' => 1,
                'details_area' => 3,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 56,
                'details_title' => 'パイレーツオブカリビアン　トランプ　限定品',
                'categories_id' => 4,
                'details_description' => 'パイレーツオブカリビアンの限定品トランプになります。海外でしか販売されていませんでした。箱は傷があります。',
                'details_price' => 1500,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 4,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 57,
                'details_title' => 'hp PC 充電コード',
                'categories_id' => 7,
                'details_description' => 'hpの充電コードになります。問題なく使えます。',
                'details_price' => 500,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 58,
                'details_title' => 'スマホスタンド',
                'categories_id' => 4,
                'details_description' => 'スマホスタンドです。クリップ式になっています。長さは60cm程です。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 6,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 59,
                'details_title' => 'メンズ　アウター',
                'categories_id' => 2,
                'details_description' => 'メンズのアウターになります。色はカーキです。サイズはSになります。',
                'details_price' => 1500,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 7,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 60,
                'details_title' => 'メンズ　ジャンバー',
                'categories_id' => 7,
                'details_description' => 'メンズのジャンバーになります。色は白、サイズはMになります。2か月ほど使用していました。',
                'details_price' => 700,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 8,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 61,
                'details_title' => 'SCANDAL CD',
                'categories_id' => 6,
                'details_description' => 'SACANDALのCDになります。5年ほど前に購入しました。付属品のTシャツはありません。',
                'details_price' => 500,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 62,
                'details_title' => '月刊少女野崎くん　1巻',
                'categories_id' => 6,
                'details_description' => '月刊少女野崎くんの1巻になります。日焼け等はありません。',
                'details_price' => 300,
                'details_state' => 1,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 63,
                'details_title' => '僕らはみんな河合荘　1巻',
                'categories_id' => 6,
                'details_description' => '僕らはみんな河合荘の1巻になります。日焼け等はありません。',
                'details_price' => 300,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 64,
                'details_title' => 'MIXAMP PRO A40',
                'categories_id' => 7,
                'details_description' => '未開封の新品です。',
                'details_price' => 10000,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 65,
                'details_title' => '推しが公認ストーカーになりました。　1~3巻',
                'categories_id' => 6,
                'details_description' => 'とても面白い漫画です。 1~3巻までのセットです。',
                'details_price' => 500,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 66,
                'details_title' => 'フィリップス　9000シリーズ　髭剃り',
                'categories_id' => 7,
                'details_description' => '未開封の新品です。　剃り心地がよさそうです。',
                'details_price' => 15000,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 67,
                'details_title' => '象印　ポッド',
                'categories_id' => 7,
                'details_description' => 'ポッドです。目立つ汚れや傷はついていません。',
                'details_price' => 1000,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 68,
                'details_title' => 'SSD 960GB',
                'categories_id' => 7,
                'details_description' => 'コンパクトサイズの960GBのSSDです。機能に問題ないです。',
                'details_price' => 6000,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 69,
                'details_title' => 'モバイルディスプレイ 15.6インチ',
                'categories_id' => 7,
                'details_description' => '15.6インチのモバイルディスプレイです。　任天堂switchにも接続できます。',
                'details_price' => 7500,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 70,
                'details_title' => 'LAN変換アダプター',
                'categories_id' => 7,
                'details_description' => 'USBにLANケーブルを差せるようにするための変換アダプターです。',
                'details_price' => 700,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 71,
                'details_title' => 'PlayStation1',
                'categories_id' => 7,
                'details_description' => '懐かしのプレステーション１です。　汚れが多少あります。',
                'details_price' => 10000,
                'details_state' => 3,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 72,
                'details_title' => 'NINTENDO64',
                'categories_id' => 7,
                'details_description' => '懐かしの任天堂の64です。　汚れが多少あります。',
                'details_price' => 5000,
                'details_state' => 3,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 73,
                'details_title' => 'SUPER FAMICOM',
                'categories_id' => 7,
                'details_description' => '懐かしのスーパーファミコンです。　箱付きです。汚れが多少あります。',
                'details_price' => 5000,
                'details_state' => 3,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 74,
                'details_title' => 'ねりけしくん',
                'categories_id' => 7,
                'details_description' => '匂い付きのねりけしです。　未開封です。',
                'details_price' => 100,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 75,
                'details_title' => 'ゲーミングチェアー',
                'categories_id' => 4,
                'details_description' => '座り心地がとてもいいゲーミングチェアーです。リクライニング付きです。',
                'details_price' => 10000,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 76,
                'details_title' => 'アコースティックギター',
                'categories_id' => 6,
                'details_description' => '汚れや傷はついていないアコギです。',
                'details_price' => 3000,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 77,
                'details_title' => 'Rain Drops シナスタジア CD',
                'categories_id' => 6,
                'details_description' => 'にじさんじに所属している6人のグループのCDです。',
                'details_price' => 1000,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 78,
                'details_title' => 'Prismatic Colors',
                'categories_id' => 6,
                'details_description' => 'にじさんじに所属しているメンバーのCDです。',
                'details_price' => 1000,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 79,
                'details_title' => '夜見れな　マグカップ',
                'categories_id' => 4,
                'details_description' => 'にじさんじに所属している夜見れなのマグカップです。',
                'details_price' => 500,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 80,
                'details_title' => 'AKH Y50 ヘッドホン',
                'categories_id' => 7,
                'details_description' => '高音質のヘッドホンです。汚れや傷は見当たりません',
                'details_price' => 3000,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 81,
                'details_title' => 'MIXAMP PRO',
                'categories_id' => 7,
                'details_description' => '音質がとてもよくなります。',
                'details_price' => 7000,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 82,
                'details_title' => 'AirPods',
                'categories_id' => 7,
                'details_description' => '未開封です。',
                'details_price' => 5000,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 83,
                'details_title' => 'R6S ヴァルキリー　フィギュア',
                'categories_id' => 4,
                'details_description' => 'R6Sに登場するキャラクター、ヴァルキリーのフィギュアです。',
                'details_price' => 1500,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 84,
                'details_title' => 'R6S IQ フィギュア',
                'categories_id' => 4,
                'details_description' => 'R6Sに登場するキャラクター、IQのフィギュアです。',
                'details_price' => 1500,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 85,
                'details_title' => 'R6S SMOKE フィギュア',
                'categories_id' => 4,
                'details_description' => 'R6Sに登場するキャラクター、SMOKEのフィギュアです。',
                'details_price' => 1500,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 86,
                'details_title' => 'YAMAHA アンプ',
                'categories_id' => 6,
                'details_description' => 'YAMAHAのアンプです。ドライブなどもいじれます。',
                'details_price' => 1500,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 87,
                'details_title' => 'ポッキーとはじめしゃちょーのキーホルダー',
                'categories_id' => 4,
                'details_description' => 'スイパラとのコラボキーホルダーです。',
                'details_price' => 500,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 88,
                'details_title' => 'Dead by Daylight PS4,海外版',
                'categories_id' => 6,
                'details_description' => 'PS4の海外版のデッドバイデイライトです。海外版のためグロいです。',
                'details_price' => 1000,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 89,
                'details_title' => 'brother　プリンター',
                'categories_id' => 7,
                'details_description' => 'brother製のプリンターです。　傷、汚れは見当たりません。',
                'details_price' => 7500,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 90,
                'details_title' => 'NIKE　シューズ',
                'categories_id' => 2,
                'details_description' => 'NIKEのロゴが入ったシューズです。少ししか使用してないのでほぼ新品です。',
                'details_price' => 8000,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 91,
                'details_title' => 'BENQ モニター',
                'categories_id' => 7,
                'details_description' => 'BENQのモニターになります。サイズは24です。画面等に傷などはありませんが、中古品であることをご考慮ください。',
                'details_price' => 3000,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 92,
                'details_title' => 'HP パソコン',
                'categories_id' => 7,
                'details_description' => 'HPのパソコンになります。一応ゲーミングパソコンです。詳しいスペックはよくわかりません。',
                'details_price' => 10000,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 93,
                'details_title' => 'Panasonic 蓄電池充電器',
                'categories_id' => 7,
                'details_description' => 'Panasonicの蓄電池充電器になります。専用の蓄電池繰り返し充電し使えます',
                'details_price' => 300,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 94,
                'details_title' => 'CYCLONE 掃除機',
                'categories_id' => 7,
                'details_description' => '充電タイプの掃除機です。問題なく使えます。',
                'details_price' => 1000,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 95,
                'details_title' => 'ハンドスチーマー',
                'categories_id' => 7,
                'details_description' => 'ケノンのハンドスチーマーになります。購入してから3度程使いました。問題なく使用できます。',
                'details_price' => 500,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 96,
                'details_title' => 'SALONIA ヘアアイロン',
                'categories_id' => 7,
                'details_description' => 'SALONIAのヘアアイロンになります。温度調節が可能です。',
                'details_price' => 700,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 97,
                'details_title' => 'sodastream 炭酸メーカー',
                'categories_id' => 7,
                'details_description' => '炭酸メーカーになります。家電量販店で炭酸ボンベを買い補充できます。',
                'details_price' => 1000,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 5,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 98,
                'details_title' => 'KOIZUMI 圧力なべ',
                'categories_id' => 7,
                'details_description' => 'KOIZUMIの圧力鍋になります。電気式です。',
                'details_price' => 1000,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 6,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 99,
                'details_title' => 'iphone 充電ケーブル',
                'categories_id' => 7,
                'details_description' => 'iphoneの充電ケーブルになります。非純正です。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 100,
                'details_title' => 'USBメモリ',
                'categories_id' => 7,
                'details_description' => 'USBメモリ。内容量は不明。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 7,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ]

        ]);
    }
}
