<?php

use Illuminate\Database\Seeder;

class DetailsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //
        DB::table('details')->insert([
            [
                'products_id' => 1,
                'details_title' => 'Laravel参考書',
                'categories_id' => 6,
                'details_description' => 'めちゃくちゃ面白い本です。最初に買って読んだときはゲラゲラ笑っていました。',
                'details_price' => 1000,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 2,
                'details_title' => '応用情報でるとこ',
                'categories_id' => 6,
                'details_description' => 'めちゃくちゃ面白い本です。最初に買って読んだときはゲラゲラ笑っていました。',
                'details_price' => 2100,
                'details_state' => 3,
                'details_shipping_fee' => 1,
                'details_area' => 2,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 3,
                'details_title' => 'チョコレート',
                'categories_id' => 5,
                'details_description' => 'ハリーポッターに出てくるチョコレートです。ダンブルドアが出てくると良いですね。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 6,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 4,
                'details_title' => 'ベビーバウンサー NewYorkBaby',
                'categories_id' => 3,
                'details_description' => 'かわいいトイ付き＆おしゃれなデニム生地のバウンサー♪
                絶妙なカーブでゆらゆら揺れて赤ちゃんごきげん！
                遊び・お昼寝・お食事さまざまなシーンで活躍します。
                面倒な組み立ての必要もなく、トイバーとホロをセットすればすぐに使えます。
                出産祝いのプレゼントなどにもおすすめです。',
                'details_price' => 5000,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 3,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 5,
                'details_title' => 'TAOTRONICS Bluetooth イヤホン',
                'categories_id' => 6,
                'details_description' => 'TAOTRONICSのBluetoothイヤホンになります。中古品になります。クリーニングしたのち発送いたします。動作確認済みです。',
                'details_price' => 4000,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 4,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 6,
                'details_title' => 'CURBX　エイムリング　130',
                'categories_id' => 6,
                'details_description' => 'CURBXのエイムリングになります。硬さは130です。使っていないものを出品します。新品未使用です。',
                'details_price' => 1500,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 7,
                'details_title' => 'レディース　パンツ',
                'categories_id' => 1,
                'details_description' => 'レディースのパンツになります。買ったっきり一度も使用していないため、きれいなほうだと思います。',
                'details_price' => 2000,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 8,
                'details_title' => 'メンズ　ジャケット　革ジャン',
                'categories_id' => 2,
                'details_description' => 'メンズの革ジャンになります。息子が使用しているもので小さくなったため出品致します。サイズはSです。ところどころ傷があります。',
                'details_price' => 1000,
                'details_state' => 3,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 9,
                'details_title' => 'ポニョ　ぬいぐるみ',
                'categories_id' => 3,
                'details_description' => 'ポニョのぬいぐるみになります。頂きもので袋に入れたままだった為きれいだと思います。',
                'details_price' => 400,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 4,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 10,
                'details_title' => '小型加湿器',
                'categories_id' => 4,
                'details_description' => '小型の加湿器になります。デザインが気に入り購入したものの加湿器としては一度も使用していません。動作確認済みではありませんが、ご了承ください。充電式です。',
                'details_price' => 700,
                'details_state' => 1,
                'details_shipping_fee' => 0,
                'details_area' => 3,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 11,
                'details_title' => 'ドラゴンズ　応援バット',
                'categories_id' => 5,
                'details_description' => 'ドラゴンズの応援バットになります。ナゴヤドームで買って一度使用したのち自宅で保管していました。',
                'details_price' => 400,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 12,
                'details_title' => 'iphone6',
                'categories_id' => 7,
                'details_description' => 'iphone6になります。携帯の買い替えのため使わなくなったため出品致します。フィルムに傷はありますが画面には傷等はありません。本体横は点々と剥げている箇所があります。中古品ですのでご理解のある方のご購入お願い致します。',
                'details_price' => 3000,
                'details_state' => 4,
                'details_shipping_fee' => 1,
                'details_area' => 7,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 13,
                'details_title' => 'レディース　バッグ',
                'categories_id' => 1,
                'details_description' => 'RODEOCROWNSのバッグになります。一度使用し自宅で保管していました。',
                'details_price' => 1000,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 6,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 14,
                'details_title' => 'メンズ　ジャケット',
                'categories_id' => 2,
                'details_description' => 'メンズのジャケットになります。サイズはSです。',
                'details_price' => 5000,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 3,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 15,
                'details_title' => 'シューズ袋　IGNIO',
                'categories_id' => 5,
                'details_description' => 'IGNIOのシューズ袋になります。体育館シューズなどが入ります。',
                'details_price' => 400,
                'details_state' => 4,
                'details_shipping_fee' => 0,
                'details_area' => 5,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 16,
                'details_title' => 'スキー手袋',
                'categories_id' => 5,
                'details_description' => 'スキー手袋になります。防水厚手なので普段使いも可能です。3で程使用しています。選択したのち配送させていただきます。',
                'details_price' => 400,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 8,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 17,
                'details_title' => 'とんでもスキルで異世界放浪メシ 6巻',
                'categories_id' => 6,
                'details_description' => 'とんでもスキルで異世界放浪メシの6巻です。一度読みそのまま保管していました。日焼け等はありません',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 1,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 18,
                'details_title' => '関数電卓',
                'categories_id' => 7,
                'details_description' => '関数電卓　傷なし汚れあり　3年間使いました',
                'details_price' => 500,
                'details_state' => 3,
                'details_shipping_fee' => 3,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 19,
                'details_title' => '電子辞書',
                'categories_id' => 7,
                'details_description' => '画面が汚れています。　返品は受け付けません。',
                'details_price' => 300,
                'details_state' => 3,
                'details_shipping_fee' => 3,
                'details_area' => 0,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 20,
                'details_title' => '折り畳み式タッチパッド付きキーボード',
                'categories_id' => 7,
                'details_description' => 'ほぼ新品です。　便利です。',
                'details_price' => 1000,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 21,
                'details_title' => 'ねんどろいど　まふまふ(引きこもりセット)',
                'categories_id' => 6,
                'details_description' => '未開封の新品です。',
                'details_price' => 1500,
                'details_state' => 0,
                'details_shipping_fee' => 3,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 22,
                'details_title' => '一番くじ　すみっコぐらし　ぬいぐるみ',
                'categories_id' => 4,
                'details_description' => '未開封の新品です。　かわいいです。',
                'details_price' => 2000,
                'details_state' => 0,
                'details_shipping_fee' => 3,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 23,
                'details_title' => '手回し発電搭載　多機能防災時計',
                'categories_id' => 7,
                'details_description' => '災害用の手回し充電の多機能防災時計です。　ライトも付いてます。',
                'details_price' => 1000,
                'details_state' => 3,
                'details_shipping_fee' => 4,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 24,
                'details_title' => 'RAGE2',
                'categories_id' => 6,
                'details_description' => 'PS4のゲームソフトです。対象年齢18歳以上です。',
                'details_price' => 500,
                'details_state' => 2,
                'details_shipping_fee' => 5,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 25,
                'details_title' => 'FARCRY3+4 ダブルパック',
                'categories_id' => 6,
                'details_description' => 'PS4のゲームソフトです。FARCRY3とFARCRY4のセットパックです。対象年齢18歳以上です。',
                'details_price' => 700,
                'details_state' => 2,
                'details_shipping_fee' => 5,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 26,
                'details_title' => 'iPhone6s',
                'categories_id' => 7,
                'details_description' => '64GB、ゴールドです。イヤホンジャックのところに多少傷があります。動作問題なし。',
                'details_price' => 3000,
                'details_state' => 2,
                'details_shipping_fee' => 7,
                'details_area' => 0,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 27,
                'details_title' => 'ヒバニー　ぬいぐるみ',
                'categories_id' => 4,
                'details_description' => 'ポケットモンスター剣盾に登場するヒバニーのぬいぐるみです。',
                'details_price' => 2000,
                'details_state' => 3,
                'details_shipping_fee' => 3,
                'details_area' => 0,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 28,
                'details_title' => 'コンデンサマイク',
                'categories_id' => 7,
                'details_description' => '開封済みですが傷なし汚れなしのほぼ新品です。音質もいいです。',
                'details_price' => 3000,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 3,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 29,
                'details_title' => 'Nintendo64 時のオカリナ',
                'categories_id' => 6,
                'details_description' => 'Nintendo64のゲームソフト、時のオカリナです。謎解きが楽しいです。',
                'details_price' => 500,
                'details_state' => 3,
                'details_shipping_fee' => 7,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 30,
                'details_title' => '3DS',
                'categories_id' => 6,
                'details_description' => 'Nintendo3DS本体です。傷、汚れ多少あり。動作問題なし。',
                'details_price' => 500,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 0,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 31,
                'details_title' => 'Android AQUOS Xx-Y',
                'categories_id' => 7,
                'details_description' => 'AQUOS Xx-Yのスマートフォンです。フィルムに傷はありますが画面には傷はありません。動作も問題ないです。',
                'details_price' => 4000,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 1,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 32,
                'details_title' => 'ジーンズ',
                'categories_id' => 1,
                'details_description' => 'レディースのジーンズです。未使用品です。',
                'details_price' => 1000,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 3,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 33,
                'details_title' => '東京喰種 1巻',
                'categories_id' => 6,
                'details_description' => '東京喰種の1巻です。汚れ、傷はありません。',
                'details_price' => 300,
                'details_state' => 1,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 34,
                'details_title' => 'メンズ　ジャンパー',
                'categories_id' => 2,
                'details_description' => 'メンズのジャンパーです。サイズはMで未使用品です。',
                'details_price' => 1000,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 3,
                'shipping_date' => 0,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 35,
                'details_title' => 'アディダス　バッグ',
                'categories_id' => 5,
                'details_description' => 'アディダスのバッグです。息子が使っていたものなので少し傷があります。',
                'details_price' => 500,
                'details_state' => 4,
                'details_shipping_fee' => 0,
                'details_area' => 2,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 36,
                'details_title' => '目覚まし時計',
                'categories_id' => 4,
                'details_description' => '目覚まし時計です。特に問題なく動作します。',
                'details_price' => 500,
                'details_state' => 2,
                'details_shipping_fee' => 1,
                'details_area' => 1,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 37,
                'details_title' => 'PS4　コントローラー',
                'categories_id' => 6,
                'details_description' => 'PS4のコントローラーです。一度しか使用していないので動作不良はありません。',
                'details_price' => 3000,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 0,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 38,
                'details_title' => 'USBメモリ 16GB',
                'categories_id' => 7,
                'details_description' => '16GBのUSBメモリです。フォーマット済みです。',
                'details_price' => 1000,
                'details_state' => 1,
                'details_shipping_fee' => 1,
                'details_area' => 2,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 39,
                'details_title' => '手袋',
                'categories_id' => 2,
                'details_description' => 'メンズの手袋です。所々に傷があります。',
                'details_price' => 500,
                'details_state' => 3,
                'details_shipping_fee' => 0,
                'details_area' => 3,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 40,
                'details_title' => 'ペン立て',
                'categories_id' => 4,
                'details_description' => 'ペン立てです。目立つ変形、傷などは特に見当たりません。',
                'details_price' => 300,
                'details_state' => 2,
                'details_shipping_fee' => 0,
                'details_area' => 4,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 41,
                'details_title' => 'ストラップ',
                'categories_id' => 3,
                'details_description' => 'アイルーのストラップです。未開封品です。',
                'details_price' => 100,
                'details_state' => 0,
                'details_shipping_fee' => 0,
                'details_area' => 4,
                'shipping_date' => 1,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 42,
                'details_title' => 'イヤホン　iPhone用',
                'categories_id' => 7,
                'details_description' => 'イヤホンです。iPhoneの付属品で、未使用品です。',
                'details_price' => 500,
                'details_state' => 0,
                'details_shipping_fee' => 1,
                'details_area' => 5,
                'shipping_date' => 2,
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ]
        ]);
    }
}
