<?php

use Illuminate\Database\Seeder;

class ImagesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        //
        DB::table('images')->insert([
            [
                'products_id' => 1,
                'images_path' => "img1.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 1,
                'image_path' => "img2.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 1,
                'image_path' => "img3.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 2,
                'image_path' => "img4.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 2,
                'image_path' => "img5.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 2,
                'image_path' => "img6.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 3,
                'image_path' => "img7.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 3,
                'image_path' => "img8.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 3,
                'image_path' => "img9.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 4,
                'image_path' => "7152987_6-e.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 4,
                'image_path' => "7152987_7-e.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 4,
                'image_path' => "7152987_8-e.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 4,
                'image_path' => "7152987_9-e.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 4,
                'image_path' => "7152987_12-e.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 5,
                'image_path' => "IMG_0419.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 5,
                'image_path' => "IMG_0420.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 5,
                'image_path' => "IMG_0421.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 6,
                'image_path' => "IMG_0368.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 6,
                'image_path' => "IMG_0369.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 6,
                'image_path' => "IMG_0370.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 7,
                'image_path' => "IMG_0371.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 7,
                'image_path' => "IMG_0372.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 7,
                'image_path' => "IMG_0373.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 8,
                'image_path' => "IMG_0380.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 8,
                'image_path' => "IMG_0381.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 8,
                'image_path' => "IMG_0382.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 9,
                'image_path' => "IMG_0383.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 9,
                'image_path' => "IMG_0384.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 9,
                'image_path' => "IMG_0385.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 10,
                'image_path' => "IMG_0386.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 10,
                'image_path' => "IMG_0387.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 10,
                'image_path' => "IMG_0388.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 11,
                'image_path' => "IMG_0389.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 11,
                'image_path' => "IMG_0390.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 11,
                'image_path' => "IMG_0391.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 12,
                'image_path' => "IMG_0392.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 12,
                'image_path' => "IMG_0393.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 12,
                'image_path' => "IMG_0394.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 12,
                'image_path' => "IMG_0395.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 13,
                'image_path' => "IMG_0396.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 13,
                'image_path' => "IMG_0397.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 13,
                'image_path' => "IMG_0398.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 14,
                'image_path' => "IMG_0399.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 14,
                'image_path' => "IMG_0400.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 14,
                'image_path' => "IMG_0401.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 15,
                'image_path' => "IMG_0402.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 15,
                'image_path' => "IMG_0403.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 15,
                'image_path' => "IMG_0404.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 16,
                'image_path' => "IMG_0405.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 16,
                'image_path' => "IMG_0406.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 16,
                'image_path' => "IMG_0407.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 17,
                'image_path' => "IMG_0408.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 17,
                'image_path' => "IMG_0409.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 17,
                'image_path' => "IMG_0410.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 18,
                'images_path' => "image0.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 19,
                'image_path' => "image1.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 19,
                'image_path' => "image2.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 19,
                'image_path' => "image3.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 20,
                'image_path' => "image4.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 20,
                'image_path' => "image5.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 20,
                'image_path' => "image6.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 21,
                'image_path' => "image7.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 21,
                'image_path' => "image8.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 21,
                'image_path' => "image9.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 21,
                'image_path' => "image10.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 21,
                'image_path' => "image11.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 21,
                'image_path' => "image12.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 21,
                'image_path' => "image13.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 22,
                'image_path' => "image14.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 22,
                'image_path' => "image15.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 22,
                'image_path' => "image16.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 23,
                'image_path' => "image17.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 23,
                'image_path' => "image18.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 23,
                'image_path' => "image19.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 23,
                'image_path' => "image20.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 24,
                'image_path' => "image21.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 25,
                'image_path' => "image22.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 26,
                'image_path' => "image23.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 26,
                'image_path' => "image24.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 26,
                'image_path' => "image25.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 27,
                'image_path' => "image26.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 28,
                'image_path' => "image27.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 28,
                'image_path' => "image28.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 29,
                'image_path' => "image29.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 29,
                'image_path' => "image30.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 30,
                'image_path' => "image31.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 30,
                'image_path' => "image32.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 30,
                'image_path' => "image33.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],[
                'products_id' => 31,
                'images_path' => "IMG-0261.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 31,
                'images_path' => "IMG-0263.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 31,
                'images_path' => "IMG-0264.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 31,
                'images_path' => "IMG-0265.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 32,
                'images_path' => "IMG-0232.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 32,
                'images_path' => "IMG-0234.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 33,
                'images_path' => "IMG-0244.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 33,
                'images_path' => "IMG-0245.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 33,
                'images_path' => "IMG-0246.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 34,
                'images_path' => "IMG-0241.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 34,
                'images_path' => "IMG-0242.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 34,
                'images_path' => "IMG-0243.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 35,
                'images_path' => "IMG-0247.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 35,
                'images_path' => "IMG-0249.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 35,
                'images_path' => "IMG-0251.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 36,
                'images_path' => "IMG-0253.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 36,
                'images_path' => "IMG-0254.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 36,
                'images_path' => "IMG-0257.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 37,
                'images_path' => "IMG-0272.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 37,
                'images_path' => "IMG-0273.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 37,
                'images_path' => "IMG-0274.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 38,
                'images_path' => "IMG-0275.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 38,
                'images_path' => "IMG-0276.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 38,
                'images_path' => "IMG-0279.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 39,
                'images_path' => "IMG-0280.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 39,
                'images_path' => "IMG-0281.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 40,
                'images_path' => "IMG-0283.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 40,
                'images_path' => "IMG-0284.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 40,
                'images_path' => "IMG-0285.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 41,
                'images_path' => "IMG-0288.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 41,
                'images_path' => "IMG-0289.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 42,
                'images_path' => "IMG-0290.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 42,
                'images_path' => "IMG-0296.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 42,
                'images_path' => "IMG-0297.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 43,
                'images_path' => "IMG_0434.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 43,
                'images_path' => "IMG_0435.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 43,
                'images_path' => "IMG_0436.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 44,
                'images_path' => "IMG_0437.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 44,
                'images_path' => "IMG_0438.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 44,
                'images_path' => "IMG_0439.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 45,
                'images_path' => "IMG_0440.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 45,
                'images_path' => "IMG_0441.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 45,
                'images_path' => "IMG_0442.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 46,
                'images_path' => "IMG_0443.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 46,
                'images_path' => "IMG_0444.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 46,
                'images_path' => "IMG_0445.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 47,
                'images_path' => "IMG_0447.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 47,
                'images_path' => "IMG_0448.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 47,
                'images_path' => "IMG_0449.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 48,
                'images_path' => "IMG_0450.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 48,
                'images_path' => "IMG_0451.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 48,
                'images_path' => "IMG_00452.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 49,
                'images_path' => "IMG_0453.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 49,
                'images_path' => "IMG_0454.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 49,
                'images_path' => "IMG_0455.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 50,
                'images_path' => "IMG_0456.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 50,
                'images_path' => "IMG_0457.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 50,
                'images_path' => "IMG_0458.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 51,
                'images_path' => "IMG_0459.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 51,
                'images_path' => "IMG_0460.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 51,
                'images_path' => "IMG_0461.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 52,
                'images_path' => "IMG_0462.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 52,
                'images_path' => "IMG_0463.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 52,
                'images_path' => "IMG_0464.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 53,
                'images_path' => "IMG_0466.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 53,
                'images_path' => "IMG_0467.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 53,
                'images_path' => "IMG_0469.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 54,
                'images_path' => "IMG_0471.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 54,
                'images_path' => "IMG_0472.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 54,
                'images_path' => "IMG_0473.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 55,
                'images_path' => "IMG_0474.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 55,
                'images_path' => "IMG_0475.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 55,
                'images_path' => "IMG_0476.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 56,
                'images_path' => "IMG_0477.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 56,
                'images_path' => "IMG_0478.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 56,
                'images_path' => "IMG_0479.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 57,
                'images_path' => "IMG_0480.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 57,
                'images_path' => "IMG_0481.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 57,
                'images_path' => "IMG_0482.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 58,
                'images_path' => "IMG_0484.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 58,
                'images_path' => "IMG_0485.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 58,
                'images_path' => "IMG_0486.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 59,
                'images_path' => "IMG_0487.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 59,
                'images_path' => "IMG_0488.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 59,
                'images_path' => "IMG_0489.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 60,
                'images_path' => "IMG_0490.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 60,
                'images_path' => "IMG_0491.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 60,
                'images_path' => "IMG_0492.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 61,
                'images_path' => "IMG_0493.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 61,
                'images_path' => "IMG_0494.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 61,
                'images_path' => "IMG_0495.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 62,
                'images_path' => "IMG_0496.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 62,
                'images_path' => "IMG_0497.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 62,
                'images_path' => "IMG_0498.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 63,
                'images_path' => "IMG_0499.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 63,
                'images_path' => "IMG_0500.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 63,
                'images_path' => "IMG_0501.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 64,
                'images_path' => "image34.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 65,
                'images_path' => "image35.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 66,
                'images_path' => "image36.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 67,
                'images_path' => "image37.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 68,
                'images_path' => "image38.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 68,
                'images_path' => "image39.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 69,
                'images_path' => "image40.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 69,
                'images_path' => "image41.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 70,
                'images_path' => "image42.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 70,
                'images_path' => "image43.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 71,
                'images_path' => "image44.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 72,
                'images_path' => "image45.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 72,
                'images_path' => "image46.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 73,
                'images_path' => "image47.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 73,
                'images_path' => "image48.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 74,
                'images_path' => "image49.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 75,
                'images_path' => "image50.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 76,
                'images_path' => "image51.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 77,
                'images_path' => "image52.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 77,
                'images_path' => "image53.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 78,
                'images_path' => "image54.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 78,
                'images_path' => "image55.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 79,
                'images_path' => "image56.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 79,
                'images_path' => "image57.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 80,
                'images_path' => "image58.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 81,
                'images_path' => "image59.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 81,
                'images_path' => "image60.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 82,
                'images_path' => "image61.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 83,
                'images_path' => "image62.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 83,
                'images_path' => "image63.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 84,
                'images_path' => "image64.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 84,
                'images_path' => "image65.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 85,
                'images_path' => "image66.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 85,
                'images_path' => "image67.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 86,
                'images_path' => "image68.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 87,
                'images_path' => "image69.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 88,
                'images_path' => "image70.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 88,
                'images_path' => "image71.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 89,
                'images_path' => "image72.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 89,
                'images_path' => "image73.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 90,
                'images_path' => "image74.jpg",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 91,
                'images_path' => "IMG_0503.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 91,
                'images_path' => "IMG_0504.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 91,
                'images_path' => "IMG_0505.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 92,
                'images_path' => "IMG_0507.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 92,
                'images_path' => "IMG_0508.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 92,
                'images_path' => "IMG_0509.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 93,
                'images_path' => "IMG_0510.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 93,
                'images_path' => "IMG_0511.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 93,
                'images_path' => "IMG_0512.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 94,
                'images_path' => "IMG_0513.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 94,
                'images_path' => "IMG_0514.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 94,
                'images_path' => "IMG_0515.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 95,
                'images_path' => "IMG_0516.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 95,
                'images_path' => "IMG_0517.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 95,
                'images_path' => "IMG_0518.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 96,
                'images_path' => "IMG_0519.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 96,
                'images_path' => "IMG_0520.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 96,
                'images_path' => "IMG_0521.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 97,
                'images_path' => "IMG_0522.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 97,
                'images_path' => "IMG_0523.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 97,
                'images_path' => "IMG_0524.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 98,
                'images_path' => "IMG_0525.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 98,
                'images_path' => "IMG_0526.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 98,
                'images_path' => "IMG_0527.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 99,
                'images_path' => "IMG_0528.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 99,
                'images_path' => "IMG_0529.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 99,
                'images_path' => "IMG_0530.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 100,
                'images_path' => "IMG_0531.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 100,
                'images_path' => "IMG_0532.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'products_id' => 100,
                'images_path' => "IMG_0533.JPG",
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ]
        ]);
    }
}
